#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hyphen
Version  : 2.8.8
Release  : 2
URL      : http://http.debian.net/debian/pool/main/h/hyphen/hyphen_2.8.8.orig.tar.gz
Source0  : http://http.debian.net/debian/pool/main/h/hyphen/hyphen_2.8.8.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: hyphen-bin
Requires: hyphen-lib
Requires: hyphen-license
Requires: hyphen-data

%description
Hyphen - hyphenation library to use converted TeX hyphenation patterns
(C) 1998 Raph Levien
(C) 2001 ALTLinux, Moscow
(C) 2006, 2007, 2008, 2010, 2011 LÃ¡szlÃ³ NÃ©meth
This was part of libHnj library by Raph Levien.
Peter Novodvorsky from ALTLinux cut hyphenation part from libHnj
to use it in OpenOffice.org.
Compound word and non-standard hyphenation support by LÃ¡szlÃ³ NÃ©meth.

License is the original LibHnj license:

%package bin
Summary: bin components for the hyphen package.
Group: Binaries
Requires: hyphen-data
Requires: hyphen-license

%description bin
bin components for the hyphen package.


%package data
Summary: data components for the hyphen package.
Group: Data

%description data
data components for the hyphen package.


%package dev
Summary: dev components for the hyphen package.
Group: Development
Requires: hyphen-lib
Requires: hyphen-bin
Requires: hyphen-data
Provides: hyphen-devel

%description dev
dev components for the hyphen package.


%package lib
Summary: lib components for the hyphen package.
Group: Libraries
Requires: hyphen-data
Requires: hyphen-license

%description lib
lib components for the hyphen package.


%package license
Summary: license components for the hyphen package.
Group: Default

%description license
license components for the hyphen package.


%prep
%setup -q -n hyphen-2.8.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533755801
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1533755801
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/hyphen
cp COPYING %{buildroot}/usr/share/doc/hyphen/COPYING
cp COPYING.LGPL %{buildroot}/usr/share/doc/hyphen/COPYING.LGPL
cp COPYING.MPL %{buildroot}/usr/share/doc/hyphen/COPYING.MPL
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/substrings.pl

%files data
%defattr(-,root,root,-)
/usr/share/hyphen/hyph_en_US.dic

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libhyphen.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhyphen.so.0
/usr/lib64/libhyphen.so.0.3.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/hyphen/COPYING
/usr/share/doc/hyphen/COPYING.LGPL
/usr/share/doc/hyphen/COPYING.MPL
